name: healthjunction
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # State Management
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  font_awesome_flutter: ^10.6.0
  # Fonts
  google_fonts: ^6.1.0
  # Native Splash Screen
  flutter_native_splash: ^2.3.3
  # Firebase
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  # Firebase For Social(Google)
  google_sign_in: ^6.1.5
  # Firebase For Phone Number Authentication
  firebase_phone_auth_handler: ^1.0.8
  #random Email OTP
  random_string: ^2.2.0
  # add url launcher dependency
  url_launcher: ^6.2.0
  # add Cloud FireStore in App
  cloud_firestore: ^4.12.1
  # add Facebook Auth in App (for Social)
  flutter_facebook_auth: ^6.0.2
  # add X(Twitter) Auth in App (for Social)
  twitter_login: ^4.4.2
  # http help to get the user data
  http: ^1.1.0
  # adding Dependencies to read data from CSV and adding it in Firebase FireStore
  csv: ^5.1.1
  # adding Animation Library
  animations: ^2.0.8

  # whatsapp api dependecy
  whatsapp: ^0.0.1
  
  excel: ^3.0.0
  add_2_calendar: ^2.1.2
  #file Picker
  file_picker: ^6.1.1
  flutter_staggered_grid_view: ^0.7.0
  firebase_storage: ^11.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  


flutter_native_splash:
  color: "#FDFDFD"
  color_dark: "#FDFDFD"
  image: assets/images/Dark Blue and Turquoise Modern Gradient Pharmacy Health Logo.png
#   image_dark: assets/images/Dark Blue and Turquoise Modern Gradient Pharmacy Health Logo.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/dataSets/blood bank private.csv
    - assets/dataSets/blood banks public.csv
    - assets/dataSets/Basic health data.csv
    - assets/dataSets/charity engos information (2).csv
    - assets/dataSets/Allied Lahore Lab.csv
    - assets/dataSets/1- chugtai.csv
    - assets/dataSets/2- islamabad diagnostic center (IDC).csv
    - assets/dataSets/3- excel labs.csv
    - assets/dataSets/4- Alnoor diagnostics center.csv
    - assets/dataSets/Indus Clinical Laboratories.csv
    - assets/dataSets/Health zone labs.csv
    - assets/dataSets/Lahore Medical Lab & Diagnostic Centre.csv
    - assets/dataSets/Registered Labs.csv
    - assets/dataSets/charity engos information new updaated (3).csv
    - assets/dataSets/PHC Hosp.csv
    - assets/dataSets/PHC LAB.csv
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
