// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDElkWJzEFuz_N6tfXlL7WPv7sAWdwwcos',
    appId: '1:293812165856:web:719d1aff818b33381bc485',
    messagingSenderId: '293812165856',
    projectId: 'health-junction-675ff',
    authDomain: 'health-junction-675ff.firebaseapp.com',
    storageBucket: 'health-junction-675ff.appspot.com',
    measurementId: 'G-B37BJLDE6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOHvvfOSZxqITqihWtD5ktgRVMkMmkkB0',
    appId: '1:293812165856:android:136b98edb48489981bc485',
    messagingSenderId: '293812165856',
    projectId: 'health-junction-675ff',
    storageBucket: 'health-junction-675ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJTHAdI3JDikY5vsAsS72iSSWY15bi2Q',
    appId: '1:293812165856:ios:bd0ac31ce876dc141bc485',
    messagingSenderId: '293812165856',
    projectId: 'health-junction-675ff',
    storageBucket: 'health-junction-675ff.appspot.com',
    androidClientId: '293812165856-2uc2hrll5ho5fcppdi7fb2nl1634g118.apps.googleusercontent.com',
    iosClientId: '293812165856-ka80elo93ebunbk6qf87o7p5q6fbpjjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthjunction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJTHAdI3JDikY5vsAsS72iSSWY15bi2Q',
    appId: '1:293812165856:ios:7e0483e1b8b28df21bc485',
    messagingSenderId: '293812165856',
    projectId: 'health-junction-675ff',
    storageBucket: 'health-junction-675ff.appspot.com',
    androidClientId: '293812165856-2uc2hrll5ho5fcppdi7fb2nl1634g118.apps.googleusercontent.com',
    iosClientId: '293812165856-h2ubapqdkl1inrhuikdqr896hth9ujf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthjunction.RunnerTests',
  );
}
