export const provinces = [
    "Punjab",
    "Sindh",
    "Balochistan",
    "Islamabad Capital Territory",
    "Khyber Pakhtunkhwa",
    "Azad Jammu and Kashmir",
    "Gilgit-Baltistan",
  ];
  
  export const departments = [
    'Emergency Department',
    'Inpatient Wards',
    'Outpatient Clinics',
    'Operating Rooms',
    'Diagnostic Imaging',
    'Laboratory Services',
    'Pharmacy',
    'Intensive Care Units',
    'Maternity And Neonatal Care',
    'Pediatrics Department',
    'Cardiology Department',
    'Neurology Department',
    'Orthopedics Department',
    'ENT Department',
    'Physical Therapy Department',
    'Occupational Therapy Department',
    'Speech Therapy Department',
    'Radiation Oncology Department',
    'Pulmonology Department',
    'Gastroenterology Department',
    'Nephrology Department',
    'Urology Department',
    'Anesthesiology Department',
    'Pathology Department',
    'Biochemistry Department',
    'Community Medicine Department',
    'Psychiatry Department', 
    'Dermatology Department', 
    'Ophthalmology Department', 
    'Oncology Department', 
    'Geriatric Department', 
    'Endocrinology Department', 
    'Hematology Department', 
    'Rheumatology Department', 
    'Allergy and Immunology Department', 
    'Microbiology Department', 
    'Forensic Medicine Department', 
    'Medical Education Department', 
    'Research and Development Department'
  ];
  
  export const facilities = [
    'Emergency Room',
    'Pharmacy',
    'Laboratory',
    'Radiology',
    'Operating Rooms',
    'Intensive Care Unit',
    'Maternity Ward',
    'Pediatric Ward',
    'Cafeteria',
    'Parking',
    'Ambulance Service',
    'Gardens/Green Spaces',
    'Fitness Center',
    'Wi-Fi Access',
    'Wheelchair Accessibility',
    'Interpreter Services',
    'Family Accommodation',
    'Counseling Services',
    'Concierge Services',
    'Dining Services',
    'Spiritual Care Services',
    'Medical Library',
    'ATM/Banking Services',
    'Gift Shop'
  ];
  
  export const services = [
    'Emergency Services',
    'Outpatient Services',
    'Inpatient Services',
    'Surgery',
    'Imaging Services',
    'Laboratory Services',
    'Pharmacy Services',
    'Physical Therapy',
    'Occupational Therapy',
    'Speech Therapy',
    'Dietary Services',
    'Social Work Services',
    'Palliative Care Services',
    'Mental Health Services',
    'Cancer Care Services',
    'Diabetes Care Services',
    'Pediatric Services',
    'Geriatric Services',
    'Neonatal Services',
    'Reproductive Health Services',
    'Travel Medicine Services',
    'Vaccination Services',
    'Dental Services',
    'Eye Care Services',
    'Digestive Health Services',
    'Endocrine Services',
    'Skin Disorder Services',
    'Respiratory Services',
    'Wound Care Services',
    'Rehabilitation Services',
    'Genetic Counseling Services',
    'Nutrition Counseling Services',
    'Stress Management Counseling Services',
    'Occupational Health Services',
    'Employee Assistance Programs',
    'Language Translation Services',
    'Legal Aid Services',
    'Financial Counseling Services'
  ];
  